sudo: reuired
services:
  - docker
  
before_install:
  - docker build -t vladimirglazachev/docker-react -f Dockerfile.dev . 

script: 
  - docker run vladimirglazachev/docker-react npm run test -- --coverage
